// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using robot.Infra.Data;

#nullable disable

namespace robot.Infra.Data.Migrations
{
    [DbContext(typeof(RobotDbContext))]
    partial class RobotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("robot.Infra.Data.Mappers.RobotDao", b =>
                {
                    b.Property<long>("RobotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RobotId"));

                    b.Property<int>("HeadAlign")
                        .HasColumnType("integer");

                    b.Property<int>("HeadDirection")
                        .HasColumnType("integer");

                    b.Property<int>("LeftElbowPosition")
                        .HasColumnType("integer");

                    b.Property<int>("LeftWristDirection")
                        .HasColumnType("integer");

                    b.Property<int>("RightElbowPosition")
                        .HasColumnType("integer");

                    b.Property<int>("RightWristDirection")
                        .HasColumnType("integer");

                    b.Property<string>("RobotName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("RobotId");

                    b.ToTable("Robots");
                });
#pragma warning restore 612, 618
        }
    }
}
